[package]
name = "filterlab"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = "0.5"
rand = "0.9.2"
rand_distr = "0.5.1"

[[bench]]
name = "read"
harness = false

[[bench]]
name = "write"
harness = false
