[package]
name = "rowlab"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
rand = "0.9.0"
rand_distr = "0.5.1"
rayon = "1.10.0"
regex = "1.11.1"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "brc"
harness = false
