[package]
name = "filterlab_ref"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
criterion = "0.5"
fxhash = "0.2"
rand = "0.8"
zipf = "7.0"

[[bench]]
name = "read"
harness = false

[[bench]]
name = "read_write"
harness = false
